import React from 'react';
import { Sparkles, AlertTriangle, TrendingUp, Activity, ScanLine } from 'lucide-react';
import type { AnalysisResult } from '@/types/codeAnalyzer';

interface Props { result: AnalysisResult }

const sevRank: Record<string, number> = { critical: 4, high: 3, medium: 2, low: 1 };

const maturityLabel = (n: number) =>
  n >= 85 ? 'Advanced' : n >= 70 ? 'Mature' : n >= 50 ? 'Developing' : 'Early';

const stabilityLabel = (n: number) =>
  n >= 85 ? 'Highly stable — safe to scale' : n >= 70 ? 'Stable with minor risks' : n >= 50 ? 'Moderate flakiness risk' : 'High flakiness risk';

const AIInsightsPanel: React.FC<Props> = ({ result }) => {
  const issues = result.issues || [];
  const topIssue = [...issues].sort((a, b) => (sevRank[b.severity] || 0) - (sevRank[a.severity] || 0))[0];

  const bestOpportunity =
    result.expectedImprovements?.[0] ||
    issues.find((i) => i.suggestion)?.suggestion ||
    'Tighten assertion quality and exception scoping for the largest reliability gain.';

  const stability = result.automationStability;

  const cards = [
    {
      icon: <AlertTriangle className="h-4 w-4" />,
      tint: 'from-rose-500/15 to-rose-500/0 text-rose-500',
      title: 'Most Critical Risk',
      body: topIssue ? topIssue.title : 'No critical risks detected in this snapshot.',
      meta: topIssue ? `${topIssue.severity.toUpperCase()}${topIssue.line ? ` · line ${topIssue.line}` : ''}` : 'Clean run',
    },
    {
      icon: <Sparkles className="h-4 w-4" />,
      tint: 'from-primary/15 to-primary/0 text-primary',
      title: 'Best Improvement Opportunity',
      body: bestOpportunity,
      meta: 'Highest expected impact',
    },
    {
      icon: <Activity className="h-4 w-4" />,
      tint: 'from-emerald-500/15 to-emerald-500/0 text-emerald-500',
      title: 'Stability Prediction',
      body: stabilityLabel(stability?.score ?? 0),
      meta: `Score ${stability?.score ?? 0}/100 · Risk ${(stability?.risk || 'low').toUpperCase()}`,
    },
    {
      icon: <TrendingUp className="h-4 w-4" />,
      tint: 'from-amber-500/15 to-amber-500/0 text-amber-500',
      title: 'Automation Maturity',
      body: `${maturityLabel(result.subScores.automationBestPractice)} — pattern adoption ${result.subScores.automationBestPractice}%`,
      meta: `Scalability ${result.subScores.scalability}%`,
    },
  ];

  return (
    <section className="hca-glass hca-glass-hover hca-rise p-5">
      <header className="flex items-center justify-between mb-4">
        <div className="flex items-center gap-2">
          <div className="h-7 w-7 rounded-lg bg-gradient-to-br from-primary/25 to-primary/5 flex items-center justify-center">
            <ScanLine className="h-3.5 w-3.5 text-primary" />
          </div>
          <h3 className="text-sm font-semibold">AI Insights</h3>
        </div>
        <span className="hca-chip"><Sparkles className="h-3 w-3 text-primary" />Generated by Hive AI</span>
      </header>
      <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
        {cards.map((c, i) => (
          <div
            key={i}
            className="relative overflow-hidden rounded-2xl border border-border/50 bg-card/60 backdrop-blur-xl p-4 hca-rise"
            style={{ animationDelay: `${i * 60}ms` }}
          >
            <div className={`absolute inset-0 bg-gradient-to-br ${c.tint} pointer-events-none opacity-90`} />
            <div className="relative">
              <div className="flex items-center gap-2 mb-1.5">
                <div className={`h-7 w-7 rounded-lg bg-background/60 backdrop-blur flex items-center justify-center ${c.tint.split(' ').pop()}`}>{c.icon}</div>
                <span className="text-[11px] uppercase tracking-wider text-muted-foreground">{c.title}</span>
              </div>
              <p className="text-sm font-medium leading-snug text-foreground/90 line-clamp-3">{c.body}</p>
              <p className="text-[11px] text-muted-foreground mt-2">{c.meta}</p>
            </div>
          </div>
        ))}
      </div>
    </section>
  );
};

export default AIInsightsPanel;
